#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/solhint-community@3.5.0/node_modules/solhint-community/node_modules:/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/solhint-community@3.5.0/node_modules:/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/solhint-community@3.5.0/node_modules/solhint-community/node_modules:/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/solhint-community@3.5.0/node_modules:/Users/nchamo/repos/permit2-adapters/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../solhint-community/solhint.js" "$@"
else
  exec node  "$basedir/../solhint-community/solhint.js" "$@"
fi
